### PR TITLE
LOGBACK-1027 - correctly handle circular suppressed and cause exceptions

### PR DESCRIPTION
**Pull request by elindsey**
Previously logback would infinitely recurse when encountering a circular reference in the cause or suppressed exception
chain.

Now it will detect circular references and output a pretty stack trace (see commit message).

Note that this stack trace differs slightly from normal Throwable.printStackTrace() behavior in that it preserves context around where the circular reference was found (ie. will still print out Suppressed or Caused by).

### CODE REVIEW

**Comment by dfjones** [comment]
Looks good to me :+1:

**Comment by elindsey** [comment]
@roykachouh there was some extra indentation for a new outer if/else, is that what you're seeing?

**Comment by phensley** [comment]
lgtm

**Comment by elindsey** [comment]
Addressed roy/roger's feedback and pushed a squashed rebase (unfortunately wiping out their original comments, d'oh)

**Pull request merged**
